package laligasantander;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static laligasantander.Club.lblID;
import static laligasantander.Club.rt1;

/**
 *
 * @author stiven
 */
public class Jugador extends javax.swing.JFrame {

    /**
     * Creates new form Clubes
     */
    public static int s;
    
    public static ResultSet rt1 = null;
    //public static ResultSet rt2 = null;
    LaLigaSantander conectar = new LaLigaSantander();
    Connection connection = conectar.conexion();
    
    public Jugador() {
        initComponents();
        this.listaJugador.removeAllItems();
        listaJugador.addItem("...Seleccionar jugador...");
        cargarVentanaJugador();
        listaPosicion.addItem("...Seleccionar posicion...");
        cargarVentanaPosicion();
        this.setTitle("Gestion de los jugadores");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lblIDClub = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblImagenJugador = new javax.swing.JLabel();
        btnSeleccionarImagen = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        listaJugador = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtIDJugador = new javax.swing.JTextField();
        listaPosicion = new javax.swing.JComboBox<>();
        txtPesoJugador = new javax.swing.JTextField();
        txtNombreJugador = new javax.swing.JTextField();
        txtEstaturaJugador = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("ID:");

        lblIDClub.setBackground(new java.awt.Color(255, 255, 255));
        lblIDClub.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblIDClub.setForeground(new java.awt.Color(0, 0, 0));
        lblIDClub.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(839, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(lblIDClub, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblIDClub))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        lblImagenJugador.setBackground(new java.awt.Color(255, 255, 255));
        lblImagenJugador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnSeleccionarImagen.setBackground(new java.awt.Color(255, 51, 51));
        btnSeleccionarImagen.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSeleccionarImagen.setText("Seleccionar imagen");
        btnSeleccionarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarImagenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(lblImagenJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(btnSeleccionarImagen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblImagenJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSeleccionarImagen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        btnRegistrar.setBackground(new java.awt.Color(255, 51, 51));
        btnRegistrar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(255, 51, 51));
        btnActualizar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(494, 494, 494)
                .addComponent(btnRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addContainerGap(488, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnActualizar)
                .addComponent(btnEliminar)
                .addComponent(btnRegistrar))
        );

        jButton1.setBackground(new java.awt.Color(255, 51, 102));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("<- Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        listaJugador.setBackground(new java.awt.Color(255, 51, 51));
        listaJugador.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        listaJugador.setForeground(new java.awt.Color(255, 255, 255));
        listaJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaJugadorActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("ID:");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nombre:");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Peso:");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Posicion:");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Estatura:");

        txtIDJugador.setBackground(new java.awt.Color(255, 255, 255));
        txtIDJugador.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtIDJugador.setForeground(new java.awt.Color(0, 0, 0));

        listaPosicion.setBackground(new java.awt.Color(255, 255, 255));
        listaPosicion.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        listaPosicion.setForeground(new java.awt.Color(0, 0, 0));
        listaPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaPosicionActionPerformed(evt);
            }
        });

        txtPesoJugador.setBackground(new java.awt.Color(255, 255, 255));
        txtPesoJugador.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtPesoJugador.setForeground(new java.awt.Color(0, 0, 0));

        txtNombreJugador.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreJugador.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtNombreJugador.setForeground(new java.awt.Color(0, 0, 0));

        txtEstaturaJugador.setBackground(new java.awt.Color(255, 255, 255));
        txtEstaturaJugador.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtEstaturaJugador.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEstaturaJugador, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                            .addComponent(txtPesoJugador)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtIDJugador)
                                .addComponent(listaPosicion, 0, 397, Short.MAX_VALUE)
                                .addComponent(txtNombreJugador)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIDJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPesoJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtEstaturaJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(listaPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listaJugador, 0, 293, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(listaJugador, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jugador().setVisible(true);
            }
        });
    }
    
    public void cargarVentanaJugador(){
        try{
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM laliga.Jugador WHERE Club_idClub = '"+Club.lblID.getText()+"';");
            while(rs.next()){
                 listaJugador.addItem(rs.getString(2));
            }
        }catch(Exception ex){
            System.out.println(ex);
        }
    }
    
    static String selectedFilePath = "";
    static String cadena = "";
    static String result = "";
    
    private void guardarImagen(){
        JFileChooser jFileChooser = new JFileChooser();
                int status = jFileChooser.showOpenDialog(Jugador.this);
                if (status == JFileChooser.APPROVE_OPTION) {
                    String selectedFilePath = jFileChooser.getSelectedFile().getAbsolutePath();
                    cadena = selectedFilePath;
                for (int i = 0; i < cadena.length(); i++) {
            if(cadena.charAt(i) == '/'){
                if(cadena.substring(cadena.length()-4,cadena.length()).equals(".png")
                        || cadena.substring(cadena.length()-4,cadena.length()).equals(".jpg")
                        || cadena.substring(cadena.length()-4,cadena.length()).equals(".bmp")
                        || cadena.substring(cadena.length()-4,cadena.length()).equals(".jpeg")){
                    result = cadena.substring(i+1,cadena.length());
                }
            }
        }
       }
                String dir =  System.getProperty("user.dir");
                File sourceFile = new File(cadena);
                File destinationFile = new File(dir + "/src/Imagenes/" + result);
                Path sourcePath = sourceFile.toPath();
                Path destinationPath = destinationFile.toPath();
                try {
                    Files.copy(sourcePath, destinationPath);
                } catch (IOException ex) {
                    ex.printStackTrace();
                }

    }
    
    public void cargarVentanaPosicion(){
        try{
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM laliga.PosicionJugador;");
            while(rs.next()){
                 listaPosicion.addItem(rs.getString(2));
            }
        }catch(Exception ex){
            System.out.println(ex);
        }
    }
    
    public void limpiar(){
        txtIDJugador.setText("");
        txtNombreJugador.setText("");
        txtPesoJugador.setText("");
        txtEstaturaJugador.setText("");
        listaPosicion.setSelectedItem(null);
        lblImagenJugador.setIcon(null);
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        Club c = new Club();
        c.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String querie = "INSERT INTO laliga.Jugador (idJugador, nombreJugador, pesoJugador, estaturaJugador, "
                      + "PosicionJugador_idPosicionJugador, Club_idClub, jugadorActivo, fotoJugador) VALUES (?,?,?,?,?,?,?,?);";
        try{
            PreparedStatement pst = connection.prepareStatement(querie);
            pst.setInt(1,Integer.parseInt(txtIDJugador.getText()));
            pst.setString(2,txtNombreJugador.getText());
            pst.setInt(3,Integer.parseInt(txtPesoJugador.getText()));
            pst.setInt(4,Integer.parseInt(txtEstaturaJugador.getText()));
            pst.setInt(5, listaPosicion.getSelectedIndex());
            pst.setInt(6, Integer.parseInt(lblIDClub.getText()));
            pst.setInt(7, 1);
            pst.setString(8,result);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Se  ha registrado un nuevo jugador \n","Insertar nuevo",JOptionPane.QUESTION_MESSAGE);
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, e.getMessage(), "Error en la conexion con la BD",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        String querie = "UPDATE laliga.jugador " +
                        "SET nombreJugador = '"+txtNombreJugador+"', " +
                        "idJugador = '"+txtIDJugador.getText()+"', " +
                        "pesoJugador = '"+txtPesoJugador.getText()+"', " +
                        "estaturaJugador = '"+txtEstaturaJugador.getText()+"', " +
                        "PosicionJugador_idPosicionJugador = '"+listaPosicion.getSelectedIndex()+"', " +
                        "Club_idClub = '"+lblIDClub.getText()+"', " +
                        "fotoJugador '"+result+"' " +
                        "WHERE idJugador = "+Integer.parseInt(txtIDJugador.getText())+";";
        try{
            PreparedStatement pst = connection.prepareStatement(querie);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Se  ha actualizado un jugador \n","Actualizar nuevo",JOptionPane.QUESTION_MESSAGE);
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, e.getMessage(), "Error en la conexion con la BD",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        dispose();
        int noActivo = 0;
        int ax = JOptionPane.showConfirmDialog(null, "¿Estas seguro que deseas eliminar a este jugador?",null, JOptionPane.YES_NO_OPTION);
        if(ax == JOptionPane.YES_OPTION){
            dispose();
            String querie = "UPDATE laliga.jugador " +
                        "SET nombreJugador = '"+txtNombreJugador+"', " +
                        "idJugador = '"+txtIDJugador.getText()+"', " +
                        "pesoJugador = '"+txtPesoJugador.getText()+"', " +
                        "estaturaJugador = '"+txtEstaturaJugador.getText()+"', " +
                        "PosicionJugador_idPosicionJugador = '"+listaPosicion.getSelectedIndex()+"', " +
                        "Club_idClub = '"+lblIDClub.getText()+"', " +
                        "jugadorActivo = " +noActivo+"," +
                        "fotoJugador '"+result+"' " +
                        "WHERE idJugador = "+Integer.parseInt(txtIDJugador.getText())+";";
        try{
            PreparedStatement pst = connection.prepareStatement(querie);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Se ha eliminado el jugador \n","Eliminar nuevo",JOptionPane.QUESTION_MESSAGE);
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, e.getMessage(), "Error en la conexion con la BD",
                    JOptionPane.ERROR_MESSAGE);
        }
        }else if(ax == JOptionPane.NO_OPTION){
            dispose();
            Jugador j = new Jugador();
            j.setVisible(true);}
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void listaJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaJugadorActionPerformed
        String list = (String) listaJugador.getSelectedItem();
        String query1 = "SELECT idJugador, nombreJugador, pesoJugador, estaturaJugador, nombrePosicionJugador, fotoJugador "
                + "FROM laliga.Jugador INNER JOIN laliga.PosicionJugador ON "
                + "(Jugador.PosicionJugador_idPosicionJugador = PosicionJugador.idPosicionJugador) WHERE nombreJugador = '" +list+"';";
        try{
            PreparedStatement pst1 = connection.prepareStatement(query1);
            rt1 = pst1.executeQuery();
            String item1 = "...Seleccionar jugador...";
            if(!listaJugador.getSelectedItem().equals(item1)){
            if(rt1.next()){
            txtIDJugador.setText(rt1.getString(1));
            txtNombreJugador.setText(rt1.getString(2));
            txtPesoJugador.setText(rt1.getString(3));
            txtEstaturaJugador.setText(rt1.getString(4));
            listaPosicion.setSelectedItem(rt1.getString(5));
            lblImagenJugador.setIcon(new ImageIcon(getClass().getResource("/Imagenes/" + rt1.getString(6))));
            }
            }else{
                limpiar();
            }
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, e.getMessage(), "Error en la conexion con la BD",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_listaJugadorActionPerformed

    private void btnSeleccionarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarImagenActionPerformed
        guardarImagen();
        JOptionPane.showMessageDialog(null, "Se ha cargado la imagen correctamente");
    }//GEN-LAST:event_btnSeleccionarImagenActionPerformed

    private void listaPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaPosicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaPosicionActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSeleccionarImagen;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    public static javax.swing.JLabel lblIDClub;
    private javax.swing.JLabel lblImagenJugador;
    private javax.swing.JComboBox<String> listaJugador;
    private javax.swing.JComboBox<String> listaPosicion;
    private javax.swing.JTextField txtEstaturaJugador;
    private javax.swing.JTextField txtIDJugador;
    private javax.swing.JTextField txtNombreJugador;
    private javax.swing.JTextField txtPesoJugador;
    // End of variables declaration//GEN-END:variables
}
